import type { Metadata } from "next";
import { Suspense } from 'react'
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import PageSuspense from "@/components/common/ui/PageSuspense";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sulala",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <ToastContainer hideProgressBar={false} newestOnTop={false} draggable className='select-none' />
        <Suspense fallback={<PageSuspense />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
